name: Cache Theos
description: Caches Theos clone and iOS SDK

inputs:
  theos_commit:
    required: true
  sdk_version:
    required: false
    default: '18.6'

outputs:
  cache-hit:
    description: Whether Theos was restored from cache
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Restore Theos cache
      id: cache
      uses: actions/cache@v5.0.5
      with:
        path: ${{ github.workspace }}/theos
        key: theos-v3-9bc73406-sdk${{ inputs.sdk_version }}

    - name: Clone Theos
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone --quiet https://github.com/theos/theos.git ${{ github.workspace }}/theos
        cd ${{ github.workspace }}/theos
        git checkout --quiet 9bc73406cf80b711ef4d02c15ff1dedc4478a275
        git submodule update --quiet --init --recursive --depth=1

    - name: Set THEOS env
      shell: bash
      run: echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

    - name: Export THEOS path
      shell: bash
      run: echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV
