name: Build YTKillerPlus IPA
on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "Bundle ID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string
        
      opensafari:
        description: "Integrate Open in YouTube (Safari Extension)"
        default: true
        required: false
        type: boolean

      demc:
        description: "Integrate DontEatMyContent"
        default: true
        required: false
        type: boolean

      youpip:
        description: "Integrate YouPiP"
        default: true
        required: false
        type: boolean

      ytuhd:
        description: "Integrate YTUHD"
        default: true
        required: false
        type: boolean

      ryd:
        description: "Integrate Return YouTube Dislikes"
        default: true
        required: false
        type: boolean

      ytabconfig:
        description: "Integrate YTABConfig"
        default: true
        required: false
        type: boolean

      youquality:
        description: "Integrate YouQuality"
        default: true
        required: false
        type: boolean

      youchoose:
        description: "Integrate YouChooseQuality"
        default: false
        required: false
        type: boolean
        
      ythold:
        description: "Integrate YTHoldForSpeed"
        default: false
        required: false
        type: boolean

      volumeboost:
        description: "Integrate VolumeBoostYT"
        default: false
        required: false
        type: boolean
        
      nativeshare:
        description: "Integrate YTNativeShare"
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTKillerPlus IPA
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: bundle_id,display_name,youpip,ytuhd,ryd,ytabconfig,youquality,demc,youchoose,ythold,volumeboost,nativeshare,opensafari

      - name: Download and Validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --quiet --no-verbose -O youtube.ipa
          file_type=$(file --mime-type -b youtube.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Get YouTube Version
        run: |
          unzip -q youtube.ipa -d ytextracted
          echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ytextracted/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
          rm -rf ytextracted
          
      - name: Get Commit Hashes
        id: commit_hashes
        uses: ./.github/actions/get-commit-hashes
        with:
          demc: ${{ inputs.demc }}
          ythold: ${{ inputs.ythold }}
          volumeboost: ${{ inputs.volumeboost }}
          nativeshare: ${{ inputs.nativeshare }}
          
      - name: Install Dependencies
        run: brew install make ldid swiftlint dpkg

      - name: Set PATH Environment Variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Cache Theos
        id: theos
        uses: ./.github/actions/cache-theos
        with:
          theos_commit: ${{ steps.commit_hashes.outputs.theos }}

      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet --depth=1 -n --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Install cyan and tbd
        run: |
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          wget --quiet --no-verbose "https://github.com/inoahdev/tbd/releases/download/2.2/tbd-mac" -O /usr/local/bin/tbd
          chmod +x /usr/local/bin/tbd

      - name: Clone Open in YouTube (Safari Extension)
        if: inputs.opensafari == true  
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension.git
          cd OpenYouTubeSafariExtension
          git sparse-checkout set --no-cone OpenYouTubeSafariExtension.appex
          git checkout
          mv *.appex ${{ github.workspace }}

      - name: Clone YouTubeHeader
        run: |
          rm -rf $THEOS/include/YouTubeHeader
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git $THEOS/include/YouTubeHeader
          if [ "${{ inputs.demc }}" = "true" ]; then
            rm -rf $THEOS/include/YTHeaders
            cp -r "$THEOS/include/YouTubeHeader" "$THEOS/include/YTHeaders"
          fi

      - name: Clone PSHeader
        run: |
          rm -rf $THEOS/include/PSHeader
          git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git $THEOS/include/PSHeader

      - name: Clone YTVideoOverlay
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoOverlay.git

      - name: Cache Tweaks
        id: cache_tweaks
        uses: ./.github/actions/cache-tweaks
        with:
          sdk_version: '18.6'
          youpip: ${{ inputs.youpip }}
          ytuhd: ${{ inputs.ytuhd }}
          ryd: ${{ inputs.ryd }}
          ytabconfig: ${{ inputs.ytabconfig }}
          youquality: ${{ inputs.youquality }}
          demc: ${{ inputs.demc }}
          ythold: ${{ inputs.ythold }}
          volumeboost: ${{ inputs.volumeboost }}
          nativeshare: ${{ inputs.nativeshare }}
          theos_commit: ${{ steps.commit_hashes.outputs.theos }}
          youpip_commit: ${{ steps.commit_hashes.outputs.youpip }}
          ytuhd_commit: ${{ steps.commit_hashes.outputs.ytuhd }}
          ryd_commit: ${{ steps.commit_hashes.outputs.ryd }}
          ygs_commit: ${{ steps.commit_hashes.outputs.ygs }}
          ytvo_commit: ${{ steps.commit_hashes.outputs.ytvo }}
          youchoose_commit: ${{ steps.commit_hashes.outputs.youchoose }}
          youshare_commit: ${{ steps.commit_hashes.outputs.youshare }}
          ytabconfig_commit: ${{ steps.commit_hashes.outputs.ytabconfig }}
          youquality_commit: ${{ steps.commit_hashes.outputs.youquality }}
          demc_commit: ${{ steps.commit_hashes.outputs.demc }}
          ytvid_commit: ${{ steps.commit_hashes.outputs.ytvid }}
          ythold_commit: ${{ steps.commit_hashes.outputs.ythold }}
          volumeboost_commit: ${{ steps.commit_hashes.outputs.volumeboost }}
          nativeshare_commit: ${{ steps.commit_hashes.outputs.nativeshare }}

      - name: Build YTVideoOverlay
        if: steps.cache_tweaks.outputs.cache_ytvo_hit != 'true'
        run: |
          cd YTVideoOverlay && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytvo.deb

      - name: Clone and Build YTKillerPlus
        run: |
          git clone --quiet --depth=1 https://github.com/mrdrvt99/YTKP.git
          cd YTKP
          echo "YTKP_VERSION=$(grep '^Version:' DEBIAN/control | awk '{print $2}')" >> $GITHUB_ENV
          chmod -R 755 .
          dpkg-deb --root-owner-group -Zgzip --build . ../ytkplus.deb

      - name: Clone and Build YouPiP
        if: inputs.youpip == true && steps.cache_tweaks.outputs.cache_youpip_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouPiP.git
          cd YouPiP && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youpip.deb

      - name: Clone and Build YTUHD
        if: inputs.ytuhd == true && steps.cache_tweaks.outputs.cache_ytuhd_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/Tonwalter888/YTUHD.git
          cd YTUHD && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytuhd.deb

      - name: Clone and Build Return-YouTube-Dislikes
        if: inputs.ryd == true && steps.cache_tweaks.outputs.cache_ryd_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git
          cd Return-YouTube-Dislikes && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ryd.deb

      - name: Clone and Build YouGroupSettings
        if: steps.cache_tweaks.outputs.cache_ygs_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git
          cd YouGroupSettings && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ygs.deb

      - name: Clone and Build YTABConfig
        if: inputs.ytabconfig == true && steps.cache_tweaks.outputs.cache_ytabconfig_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git
          cd YTABConfig && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytabconfig.deb

      - name: Clone and Build YouQuality
        if: inputs.youquality == true && steps.cache_tweaks.outputs.cache_youquality_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouQuality.git
          cd YouQuality && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youquality.deb

      - name: Clone and Build YouChooseQuality
        if: inputs.youchoose == true && steps.cache_tweaks.outputs.cache_youchoose_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/Tonwalter888/YouChooseQuality.git
          cd YouChooseQuality && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youchoose.deb

      - name: Clone and Build YouShare
        if: steps.cache_tweaks.outputs.cache_youshare_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/Tonwalter888/YouShare.git
          cd YouShare && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youshare.deb

      - name: Clone and Build DontEatMyContent
        if: inputs.demc == true && steps.cache_tweaks.outputs.cache_demc_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/therealFoxster/DontEatMyContent.git
          cd DontEatMyContent && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/demc.deb

      - name: Clone and Build YTVideoErrorAlert
        if: steps.cache_tweaks.outputs.cache_ytvid_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoErrorAlert.git
          cd YTVideoErrorAlert && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytvideoerror.deb
          
      - name: Clone and Build YTHoldForSpeed
        if: inputs.ythold == true && steps.cache_tweaks.outputs.cache_ythold_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/joshuaseltzer/YTHoldForSpeed.git
          cd YTHoldForSpeed && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless ARCHS=arm64 TARGET=iphone:clang:latest:15.0 
          mv packages/*.deb ${{ github.workspace }}/ythold.deb

      - name: Clone and Build VolumeBoostYT
        if: inputs.volumeboost == true && steps.cache_tweaks.outputs.cache_volumeboost_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/VasirakCalgux/VolumeBoostYT.git
          cd VolumeBoostYT && make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless ARCHS=arm64
          mv packages/*.deb ${{ github.workspace }}/volumeboost.deb
          
      - name: Clone and Build YTNativeShare
        if: inputs.nativeshare == true && steps.cache_tweaks.outputs.cache_nativeshare_hit != 'true'
        run: |
          git clone --quiet --depth=1 https://github.com/jkhsjdhjs/youtube-native-share.git
          cd youtube-native-share
          git clone --quiet --depth=1 https://github.com/protocolbuffers/protobuf.git
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless ARCHS=arm64
          mv packages/*.deb ${{ github.workspace }}/nativeshare.deb

      - name: Inject Tweaks Into IPA
        run: |
          tweaks=""
          if [ "${{ inputs.opensafari }}" = "true" ] && [ -e "OpenYouTubeSafariExtension.appex" ]; then
            tweaks="OpenYouTubeSafariExtension.appex"
          fi
          for f in *.deb; do
            [ -f "$f" ] && tweaks="$tweaks $f"
          done
          cyan -i youtube.ipa -o YTKillerPlus_${{ env.YT_VERSION }}_${{ env.YTKP_VERSION }}.ipa -uwesf $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}
                    
      - name: Create a Draft Release
        uses: softprops/action-gh-release@v2.6.2
        with:
          tag_name: ytkp-ipa${{ github.run_number }}
          name: YTKillerPlus_${{ env.YT_VERSION }}_${{ env.YTKP_VERSION }} (${{ github.run_number }})
          files: YTKillerPlus_${{ env.YT_VERSION }}_${{ env.YTKP_VERSION }}.ipa
          draft: true

      - name: Job Summary - Build Complete
        run: echo -e '### 🛠️ Build YTKillerPlus IPA Complete!' >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output the Draft Release Link
        run: |
          echo -e "### 🚀 Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases" >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Cleanup
        run: |
          echo -e "### 🧹 Cleanup\n\nYou can remove previous GitHub Actions run here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-workflows-run.yml And if you want to delete old draft releases you have then here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-draft-releases.yml" >> $GITHUB_STEP_SUMMARY
